### ISSUE TITLE
✨ add different strategies for module synchronization

### ISSUE THREAD

**Issue by jeftadlvw** [jeftadlvw/git-nest#11]
The current synchronization behaviour is fixed. If a submodule does not exist at it's set location, the configuration is chosen as the source of truth and the module is cloned. But if the module already exists, the module is set as the source of truth and the configuration is changed.

It should be possible to define and set this behaviour in the configuration with an optional field:
```toml
[[submodule]]
  path = "path/to/repository"
  url = "https://url/to/repository"
  sync = "SYNC_STRATEGY"
```

It should also be a flag when synchronizing single submodules (#9) for setting the strategy temporarily.
