### ISSUE TITLE
🔧 git-nest configuration (`nestmodules.toml`)

### ISSUE THREAD

**Issue by jeftadlvw** [jeftadlvw/git-nest#4]
In order for `git-nest` to work, a configuration file is needed. Technically `.gitmodules` from `git submodule` offers an already existing configuration file, but in the near future other configurations may be needed. This is why this issue proposes a configuration format: `nestmodules.toml`.

```toml
[config]
  # future configuration here

[[submodule]]
  path = "path-to-submodule"
  url = "https://url/to/repository"
  ref = "branch, tag or commit"
```

Using the _toml_ configuration language (https://toml.io) offers a well-known and [well-supported](https://github.com/toml-lang/toml/wiki) syntax that leaves enough room for future changes.

The `nestmodules.toml`-file should be located at the project's root directory or within a `.config` subdirectory. If it does not exist, `git-nest` creates it at the root directory.

Submodules are declared as an [array of tables](https://toml.io/en/v1.0.0#array-of-tables) with three values:
- `path`: path to local subdirectory where module is located
- `url`: remote repository url of module
- `ref`: version of repository to check out

Both `path`and `url` are required keys, wheras `ref` is optional.

This specification will most likely go through some iterations. It will be stable with version `1.0.0`.
