### ISSUE TITLE
✨ named submodules

### ISSUE THREAD

**Issue by jeftadlvw** [jeftadlvw/git-nest#9]
Add a required name to each submodule configuration. This could help when specifying some behaviour.

```toml
[[submodule]]
  name = "foo"
  path = "path/to/repository"
  url = "https://url/to/repository"
  ref = "branch, tag or commit"
```

Now, you have a generic way of addressing the submodules for commands like `remove` and mabye later `sync`.
